import type { SavingsPlan } from './types';

export const MOCK_PLANS: SavingsPlan[] = [
  {
    id: 'mock-vacation',
    name: 'Vacation Fund',
    category: 'vacation',
    type: 'individual',
    token: 'USDC',
    chain: 'base',
    targetAmount: 2000,
    currentAmount: 840,
    myContribution: 840,
    partnerContribution: 0,
    yieldEarned: 3.412,
    apy: 4.8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    isPartnerAccepted: false,
    lockDurationDays: 90,
    withdrawalDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 76).toISOString(),
    depositToDefi: true,
    policyAgreed: true,
    sharedOnX: false,
  },
  {
    id: 'mock-rent',
    name: 'Rent & Bills',
    category: 'rent',
    type: 'joint',
    token: 'USDC',
    chain: 'arbitrum',
    targetAmount: 5000,
    currentAmount: 2150,
    myContribution: 1200,
    partnerContribution: 950,
    yieldEarned: 8.224,
    apy: 5.2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    isPartnerAccepted: true,
    partnerInviteCode: 'EQV-A1B2C3D4',
    lockDurationDays: 30,
    withdrawalDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 1).toISOString(),
    depositToDefi: true,
    policyAgreed: true,
    sharedOnX: false,
  },
];
